/* 
 * fraudapi
 *
 * Easily and directly scan and block fraudulent security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.FraudDetection.Api;
using Cloudmersive.APIClient.NET.FraudDetection.Model;
using Cloudmersive.APIClient.NET.FraudDetection.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.FraudDetection.Test
{
    /// <summary>
    ///  Class for testing AdvancedFraudDetectionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AdvancedFraudDetectionResultTests
    {
        // TODO uncomment below to declare an instance variable for AdvancedFraudDetectionResult
        //private AdvancedFraudDetectionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AdvancedFraudDetectionResult
            //instance = new AdvancedFraudDetectionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AdvancedFraudDetectionResult
        /// </summary>
        [Test]
        public void AdvancedFraudDetectionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AdvancedFraudDetectionResult
            //Assert.IsInstanceOfType<AdvancedFraudDetectionResult> (instance, "variable 'instance' is a AdvancedFraudDetectionResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Test]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }
        /// <summary>
        /// Test the property 'FraudRiskLevel'
        /// </summary>
        [Test]
        public void FraudRiskLevelTest()
        {
            // TODO unit test for the property 'FraudRiskLevel'
        }
        /// <summary>
        /// Test the property 'ContainsFinancialLiability'
        /// </summary>
        [Test]
        public void ContainsFinancialLiabilityTest()
        {
            // TODO unit test for the property 'ContainsFinancialLiability'
        }
        /// <summary>
        /// Test the property 'ContainsSensitiveInformationCollection'
        /// </summary>
        [Test]
        public void ContainsSensitiveInformationCollectionTest()
        {
            // TODO unit test for the property 'ContainsSensitiveInformationCollection'
        }
        /// <summary>
        /// Test the property 'ContainsAssetTransfer'
        /// </summary>
        [Test]
        public void ContainsAssetTransferTest()
        {
            // TODO unit test for the property 'ContainsAssetTransfer'
        }
        /// <summary>
        /// Test the property 'ContainsPurchaseAgreement'
        /// </summary>
        [Test]
        public void ContainsPurchaseAgreementTest()
        {
            // TODO unit test for the property 'ContainsPurchaseAgreement'
        }
        /// <summary>
        /// Test the property 'ContainsEmploymentAgreement'
        /// </summary>
        [Test]
        public void ContainsEmploymentAgreementTest()
        {
            // TODO unit test for the property 'ContainsEmploymentAgreement'
        }
        /// <summary>
        /// Test the property 'ContainsExpiredDocument'
        /// </summary>
        [Test]
        public void ContainsExpiredDocumentTest()
        {
            // TODO unit test for the property 'ContainsExpiredDocument'
        }
        /// <summary>
        /// Test the property 'AnalysisRationale'
        /// </summary>
        [Test]
        public void AnalysisRationaleTest()
        {
            // TODO unit test for the property 'AnalysisRationale'
        }
        /// <summary>
        /// Test the property 'DocumentClass'
        /// </summary>
        [Test]
        public void DocumentClassTest()
        {
            // TODO unit test for the property 'DocumentClass'
        }

    }

}
