/* 
 * fraudapi
 *
 * Easily and directly scan and block fraudulent security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.FraudDetection.Client;
using Cloudmersive.APIClient.NET.FraudDetection.Api;
using Cloudmersive.APIClient.NET.FraudDetection.Model;

namespace Cloudmersive.APIClient.NET.FraudDetection.Test
{
    /// <summary>
    ///  Class for testing FraudDetectionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FraudDetectionApiTests
    {
        private FraudDetectionApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FraudDetectionApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FraudDetectionApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FraudDetectionApi
            //Assert.IsInstanceOfType(typeof(FraudDetectionApi), instance, "instance is a FraudDetectionApi");
        }

        
        /// <summary>
        /// Test DocumentDetectFraud
        /// </summary>
        [Test]
        public void DocumentDetectFraudTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream inputFile = null;
            //var response = instance.DocumentDetectFraud(inputFile);
            //Assert.IsInstanceOf<FraudDetectionResult> (response, "response is FraudDetectionResult");
        }
        
        /// <summary>
        /// Test DocumentDetectFraudAdvanced
        /// </summary>
        [Test]
        public void DocumentDetectFraudAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userEmailAddress = null;
            //bool? userEmailAddressVerified = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.DocumentDetectFraudAdvanced(userEmailAddress, userEmailAddressVerified, inputFile);
            //Assert.IsInstanceOf<AdvancedFraudDetectionResult> (response, "response is AdvancedFraudDetectionResult");
        }
        
    }

}
